### ISSUE TITLE
issues when building tools and tests

### ISSUE THREAD

**Issue by psmatter** [doe300/VC4CL#114]
When linking the v3d_info tool, the linker complains with unresolved externals. 

Patching  -Wl,--no-as-needed -ldl -pthread manually into build/tools/CMakeFiles/v3d_info.dir/link.txt  solves the issue. 

When building the tests, TestData.h is missing. 

(using a raspi running bullseye)

**Comment by doe300** [comment]
What are the externals that are not found?

**Comment by psmatter** [comment]
When building Tests from add_subdirectory(test) in the CMakefile.txt,   test.cpp and TestExecutions.cpp miss TestData.h

**Comment by psmatter** [comment]
Sorry, you asked for the unresolved externals. I didnt note them. pthread_create as far as I remember and dlopen to dlsym.

**Comment by psmatter** [comment]
Just cloned the repository and compiled again, but now everything compiles fine. Might eventually come from me compiling VC4CL prior to VC4CLStdLib and VC4C.

**Comment by psmatter** [comment]
Just confirmed. TestData.h is in the VC4C/test directory. Also the unresolved externals are gone. Was def the wrong way to start with VC4CL. Up and running now:
clinfo -l
Platform #0: OpenCL for the Raspberry Pi VideoCore IV GPU
   Device #0: VideoCore IV GPU

Thanks a lot and sorry for the inconvenience!
