### ISSUE TITLE
CI failed

### ISSUE THREAD

**Issue by nomaddo** [doe300/VC4CL#26]
Somehow circleci build failed.
Probably, getting URL by `curl` in `get vc4c url` make empty json file, then `get vc4cl-stdlib package` failed because of empty json file.
https://circleci.com/gh/doe300/VC4CL/28

**Comment by doe300** [comment]
Seems like the problem is that the latest build is always the `test-spirv` build, which has no artifacts...

**Comment by nomaddo** [comment]
Thanks. So we need more complex script that get the URL....

**Comment by nomaddo** [comment]
Fixed in #28
