### ISSUE TITLE
Kernel Float  Multiplication Bug

### ISSUE THREAD

**Issue by JelixLi** [doe300/VC4CL#37]
when I write code like
<code>
int i;
int j;
int k=i * j;
</code>
I can't get correct results
but if I write
<code>
int i;
int k=i * 10;
</code>
The result is correct, what's  wrong with the multiplication between two variables?

**Comment by JelixLi** [comment]
And it seems that only "int"  has this problem

**Comment by doe300** [comment]
The VideoCore IV hardware does not support full-width 32-bit integer multiplication, so we have to emulate it with multiple 24.bit multiplications, additions and shifts, which may be wrong in some cases. The second example (multiplication with a constant) may be optimized to generate different code.
In contrast, floating-point multiplication is supported on the VC4 and therefore should yield the correct result.

**Comment by JelixLi** [comment]
All right. Thanks for your feedback !
