### ISSUE TITLE
VC4CL not compatible with VC4 mesa experimental Raspberry PI driver and Qt 

### ISSUE THREAD

**Issue by pnduffy** [doe300/VC4CL#60]
When I run my QtApp which is linked to run the Experimental VC4 (full KMS) driver and OpenGL, I get a blue screen when running OpenCL with OpenCV.    It appears the mesa driver and VC4CL are stomping on each other and are not compatible.

**Comment by doe300** [comment]
What do you mean by blue screen?

How did you compile VC4C? Did you build with the CMake configuration `REGISTER_POKE_KERNELS` enabled or disabled? With `REGISTER_POKE_KERNELS` enabled, they won't work together. Even with the configuration disabled, it is not guaranteed that they can work together.

See also #51 .
