### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by aaguiar96** [doe300/VC4CL#62]
Hello.

I installed all in ubuntu 18.04 and confirmed that VC4C is working.
However, while creating a cl::Buffer I get this error message:
```
[VC4CL] test_cl.o: ioctl_set_msg failed: -1
[VC4CL] Error in mbox_propertie: Inappropriate ioctl for device
```

Any idea what this may be?
Thanks in advance.

**Comment by doe300** [comment]
Did you install Raspbian or a "vanilla" Ubuntu?

OSes other than Raspbian do not provide the mailbox driver and the accompanying character device to communicate with the firmware.

**Comment by aaguiar96** [comment]
I installed Ubuntu because I need to work on it...

Is it possible to install those things in Ubuntu?

**Comment by doe300** [comment]
You will need to provide the Raspberry PI [userland](https://github.com/raspberrypi/userland) and [firmware](https://github.com/raspberrypi/firmware) and also probably the correct kernel module, see [here](https://github.com/doe300/VC4CL/issues/53#issuecomment-457687444) and [here](https://github.com/doe300/VC4CL/issues/53#issuecomment-457706381).
