### ISSUE TITLE
Installed as VC4C but the vc4c.postinst script expects vc4c

### ISSUE THREAD

**Issue by ab1jx** [doe300/VC4CL#63]
That seems be be the bulk of the problem, see https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=194952&p=1446371#p1446371

It kept showing up as a broken package according to Raspbian/Debian standards because the config step failed.  I just symlinked VC4C to vc4c and triggered a fix of broken packages which ran the final config step.

**Comment by doe300** [comment]
Should be fixed now with latest master (or latest package)
