### ISSUE TITLE
OpenCV with VC4CL

### ISSUE THREAD

**Issue by Cyper77** [doe300/VC4CL#70]
First of all sorry, i have many dumb questions for that:
.We know opencv support opencl with many functions like cv::gpu::***, cv::umat::***, cv::ocl::*** eg..
 but i dont know how opencv compile each functions for opencl, or these compiled before?

.Opencl works with compiled gpu kernels, but how can i pick necessery opencv functions in my project for this compile? now i dont know too or how ??

.Finally, i assumed part of the opencv libs precompiled for vc4 opencl, good but how can we use it without compile procedure and what is ram usage for gpu ? (64mb std. for pi)
thanks a lot.

**Comment by doe300** [comment]
> but i dont know how opencv compile each functions for opencl, or these compiled before?
> .Opencl works with compiled gpu kernels, but how can i pick necessery opencv functions in my project for this compile?

This should be automatically handled by the OpenCL application (in this case OpenCV).

> .Finally, i assumed part of the opencv libs precompiled for vc4 opencl, good but how can we use it without compile procedure and what is ram usage for gpu ? (64mb std. for pi)

Again, whether or not the kernel code is precompiled (either into machine code or an intermediate format) is in the hand of the OpenCL application (OpenCV). The GPU memory split required depends on what kernels you want to execute. In case of OpenCV, I don't know how much you need.
