### ISSUE TITLE
Works with an ARMv6 (ie RPi Zero) ?

### ISSUE THREAD

**Issue by Aradena** [doe300/VC4CL#71]
Hi  
Never run anything on a GPU, new to opencl, but trying to learn ! 
Just to be sure :  Does this implementation work on the Broadcom BCM2835(armv6) CPU ? 
thks

**Comment by doe300** [comment]
Should work on all Raspberry Pis. It could be possible, that the prebuilt packages does not support all (esp. older) models, but if you compile from source, it should work on all models.
