### ISSUE TITLE
OpenCL on the VideoCore VI

### ISSUE THREAD

**Issue by Bobrow** [doe300/VC4CL#79]
I was wondering as the rpi 4 has a VC6 GPU, would VC4CL work with it or does someone need to make a version for it?

**Comment by nktl** [comment]
Just tried this, unfortunately precompiled dpkgs and build process itself are rather broken since Pi4 uses Debian Buster, which for instance does not have clang 3.9 any more

It does look like it will require some work - and who knows at this point how much VideoCore VI is different from IV...

**Comment by Terminus-IMRC** [comment]
Although TMU, uniform, VPM and so forth is still there, the instruction set of VC6 has been renewed from VC4 and some new functions such as MMU is introduced. Some of the changes and instruction sets are open-sourced in [https://cgit.freedesktop.org/mesa/mesa/tree/src/broadcom](https://cgit.freedesktop.org/mesa/mesa/tree/src/broadcom), but a detailed reference manual is not published yet. Gordon Hollingworth says that it would be available [https://twitter.com/gsholling/status/1143069972106817536](https://twitter.com/gsholling/status/1143069972106817536).

**Comment by doe300** [comment]
> Although TMU, uniform, VPM and so forth is still there, the instruction set of VC6 has been renewed from VC4 and some new functions such as MMU is introduced.

Exactly. I don't know that much details about the VC6, but at least the VC5 (from what I can see from the mesa driver) has a lot of changes which make it a lot easier to work with but would also need a lot of rewriting/additional support.

**Comment by hagom** [comment]
What's the status of the VC6 support for pi4 ?

**Comment by doe300** [comment]
There won't be any, at least not via this library. For the VideoCore VI, probably your best chance is the official mesa graphics library and either use OpenGL/Vulkan directly or try one of https://github.com/google/clspv or https://github.com/kpet/clvk as wrappers.

**Comment by hagom** [comment]
this is sad because the pi 4 has more than a year and it is incredible that the SBC doesn't have fully support for the GPU
