### ISSUE TITLE
v3d_info linking fails (symbols from libbcm_host not found)

### ISSUE THREAD

**Issue by senshu** [doe300/VC4CL#8]
When building VC4CL, I get:

```
Linking CXX executable v3d_info
../libVC4CL.so.0.4: undefined reference to `bcm_host_get_peripheral_address'
../libVC4CL.so.0.4: undefined reference to `bcm_host_init'
../libVC4CL.so.0.4: undefined reference to `bcm_host_deinit'
```

Linking succeeds if I modify `tools/CMakeLists.txt`, adding `libbcm_host` to the libraries for `v3d_info` as follows:

```cmake
target_link_libraries(v3d_info VC4CL ${BCMHOST_LIBRARY})
```

**Comment by doe300** [comment]
Strange, `libbcm_host` is already linked in the shared library `libVC4CL`, so the symbols should be available for `v3d_info`.

Have you done anything special with the build-configuration (e.g. cross compilation, out-of-source build)?

**Comment by senshu** [comment]
I have tried to rebuild from scratch to confirm the issue but I cannot reproduce it...

> Have you done anything special with the build-configuration (e.g. cross compilation, out-of-source build)?

I'm building in a VM with a customized Raspbian Stretch, so I assume that the problem is in my setup.

**Comment by senshu** [comment]
Just tried again on an official Raspbian Stretch image.
No linking error.
